- name: Copies network manger and watchdog
  copy:
    owner: root
    group: root
    mode: 0755
    src: "{{ item }}"
    dest: "/usr/sbin/{{ item }}"
  with_items:
    - cast_viewer_net_mgr.py
    - cast_viewer_net_watchdog.py

- name: Copies network manager unit file
  copy:
    owner: root
    group: root
    src: cast-viewer-net-manager.service
    dest: /etc/systemd/system/cast-viewer-net-manager.service

- name: Copies network watchdog service file
  copy:
    owner: root
    group: root
    src: cast-viewer-net-watchdog.service
    dest: /etc/systemd/system/cast-viewer-net-watchdog.service

- name: Copies network watchdog timer file
  copy:
    owner: root
    group: root
    src: cast-viewer-net-watchdog.timer
    dest: /etc/systemd/system/cast-viewer-net-watchdog.timer

- name: Copies in sample network.ini file
  copy:
    owner: root
    group: root
    mode: 0644
    src: network.ini-sample
    dest: /boot/network.ini
    force: no

- name: Copies the ntp.conf
  copy:
    owner: root
    group: root
    mode: 0644
    src: ntp.conf
    dest: /etc/ntp.conf
    force: yes

- name: Activate network manager
  command: systemctl enable cast-viewer-net-manager.service chdir=/etc/systemd/system

- name: Activate network watchdog
  command: systemctl enable cast-viewer-net-watchdog.timer chdir=/etc/systemd/system

- name: Remove Hamachi
  apt: pkg=logmein-hamachi
       state=absent

- name: Zerotier GPG key
  apt_key:
    keyserver: pgp.mit.edu
    id: 23E52A61

- name: Zerotier repository
  apt_repository:
    repo: deb https://download.zerotier.com/debian/jessie jessie main
    state: present

- name: Zerotier
  apt:
    name: zerotier-one
    state: present
    update_cache: yes

- name: Enable zerotier service
  service:
    name: zerotier-one
    enabled: true
    state: started

- name: Join zerotier network
  shell: /usr/sbin/zerotier-cli join 17d709436cf23366
  register: command_result
  retries: 3
  delay: 3
  until: command_result | success

- name: Restart network services
  command: /bin/true
  notify:
    - cast-viewer-net-manager
    - cast-viewer-net-watchdog

- name: Allow SSH
  ufw: rule=allow port=22 proto=tcp

- name: Set firewall default policy
  ufw: state=enabled policy=reject
