- name: Install pip dependencies
  pip:
    chdir: "{{ playbook_dir }}/../"
    requirements: requirements.txt

- name: Ensure cast-viewer is owned by pi:pi
  file:
    path: /home/pi/cast-viewer
    owner: pi
    group: pi
    recurse: yes
    state: directory

- name: Copy cast systemd units
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items: "{{ cast_viewer_systemd_units }}"

- name: Enable cast systemd services
  command: systemctl enable {{ item }} chdir=/etc/systemd/system
  with_items: "{{ cast_viewer_systemd_units }}"

- name: Update cronjob
  cron:
    name: Update cronjob
    minute: '*/30'
    job: PATH=/usr/bin:/usr/local/bin /usr/bin/flock -n /tmp/cast-viewer-update.lock -c '/usr/bin/sudo /bin/bash /home/pi/cast-viewer/bin/update.sh'

- name: Restart services
  command: /bin/true
  notify:
    - restart-cart-viewer
